import Head from 'next/head'
import MainLayout from '../components/layouts/MainLayout'

export default function Home() {
	return (
		<MainLayout title="Inicio">
			<Head>
				<title>Ref App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				
			</div>

		</MainLayout>
	)
}